services:
  api:
    container_name: medea-api
    build: .
    ports:
      - "8000:8000"

  db:
    image: postgres
    container_name: medea-db
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: medea
      POSTGRES_DB: dev
    ports:
      - "8001:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4
    container_name: medea-pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: medea
    ports:
      - "8002:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pg-data:
  pgadmin-data:
