name: Continuous Integration Pipeline
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.2'
      - name: Build application
        run: go build -o medea/api ./...
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: api
          path: medea

  run:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: api
          path: medea
      - name: Run application
        id: run-application
        run: ./medea/api
